name: Test python

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  checks: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -v pytest

    - name: Run tests
      run: |
        pytest -rp calculator_pytest.py > Pytests${{ github.run_number }}.txt
    - name: Run unittests
      run: |
        python -m unittest -v calculator_unittest.py > unittests${{ github.run_number }}.txt
    - name: Commit files
      run: |
        git config --local user.email "armangrig.ag@gmail.com"
        git config --local user.name "Arman"
        git add Pytests${{ github.run_number }}.txt unittest_results.txt
        git commit -m "Tests ${{ github.run_number }}.txt"
        git push
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
  run_calculator:
    needs: tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Run calculator
      run: python calculator.py
